# Generated by Django 3.2.10 on 2022-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_registeremployer_isverified_delete_openjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeremployer',
            name='job_closed',
            field=models.BooleanField(default=False),
        ),
    ]
